### ISSUE TITLE
New refsDecl format defined in MyCapytain?

### ISSUE THREAD

**Issue by sonofmun** [Capitains/guidelines#4]
The only place that I see in MyCapytain where the refsDecl of an XML file is found is at https://github.com/Capitains/MyCapytain/blob/3ff0f27e514f5895d4f83dbe294d4035a9e4dc53/MyCapytain/resources/texts/local/capitains/cts.py#L477-L488, where the `@n='CTS'` is hardcoded. But in the guidelines it says that the `@n` of the refsDecl should be 'capitains'. Where is this defined in MyCapytain?

**Comment by PonteIneptique** [comment]
I was gonna reply to the HookTest thingie but this part of the new guidelines are not fixed. I think the most urgent matter would be the metadata guidelines and not these. But not sure.

**Comment by PonteIneptique** [comment]
By not fixed, I meant that it's not finalized, sorry.
Metadata files : final, with a nice XML schema.
Text files: not finalized. But `@n="capitains"` will definitely be the system.

**Comment by sonofmun** [comment]
Good. I can change tests for refsDecl on HookTest when MyCapytain has been upgraded to include this stuff. For now, I can implement the tests on the metadata files.
